version: '3'
services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    #restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: '1234'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'admin'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - ./data:/var/lib/mysql
    networks:
      main_network:
  mysql-workbench:
    image: ghcr.io/linuxserver/mysql-workbench
    container_name: mysql-workbench
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./workbench/config:/config
    ports:
      - 3000:3000
    cap_add:
      - IPC_LOCK
    #restart: unless-stopped
    networks: 
      main_network:

networks: # network sections, here we can create or define an existing network
  main_network: #define here a network
    external: true # it means that we have already created this network
